ktor:
  development: $DEV
  deployment:
    host: $HOST
    sslPort: $SSL_PORT
  application:
    modules:
      - com.mypasswordgen.server.ServerKt.module
  security:
    ssl:
      keyStore: $KEY_STORE
      keyAlias: $KEY_ALIAS
      keyStorePassword: $KEY_STORE_PASSWORD
      privateKeyPassword: $PRIVATE_KEY_PASSWORD

postgres:
  username: $POSTGRES_USER
  password: $POSTGRES_PASSWORD
  driver: org.postgresql.Driver
  jdbcUrlBase: "jdbc:postgresql"
  host: $POSTGRES_HOST
  port: $POSTGRES_PORT
  database: $POSTGRES_DB
