ktor:
  development: true
  deployment:
    host: 0.0.0.0
    sslPort: 8443
  application:
    modules:
      - com.lucasmdjl.passwordgenerator.server.ServerKt.module
  security:
    ssl:
      keyStore: keystore/localhost.jks
      keyAlias: localhost
      keyStorePassword: localhosttest
      privateKeyPassword: localhosttest

postgres:
  username: postgres
  password: postgres
  driver: org.postgresql.Driver
  jdbcUrlBase: "jdbc:postgresql"
  host: $POSTGRES_HOST
  port: 5432
