version: '1'

services:
  database:
    image: 'postgres:14.5-alpine'
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: default_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data