version: '1'

services:
  web:
    build:
      context: .
      args:
        SSL_PORT: ${SSL_PORT}
    environment:
      DEV: ${DEV}
      HOST: ${HOST}
      SSL_PORT: ${SSL_PORT}
      POSTGRES_HOST: database
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      KEY_STORE: ${KEY_STORE}
      KEY_ALIAS: ${KEY_ALIAS}
      KEY_STORE_PASSWORD: ${KEY_STORE_PASSWORD}
      PRIVATE_KEY_PASSWORD: ${PRIVATE_KEY_PASSWORD}
    ports:
      - 8443:${SSL_PORT}
    depends_on:
      - database
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  database:
    image: 'postgres:14.1-alpine'
    ports:
      - 5432:${POSTGRES_PORT}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
