version: '1'

services:
  web:
    build:
      context: .
      args:
        SSL_PORT: ${SSL_PORT}
    env_file:
      - .env
    ports:
      - 8443:${SSL_PORT}
    depends_on:
      - database
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  database:
    image: 'postgres:14.1-alpine'
    ports:
      - 5432:${POSTGRES_PORT}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
