ktor:
  development: true
  deployment:
    environment:
      host: localhost
      sslPort: 8443
  application:
    modules:
      - com.lucasmdjl.passwordgenerator.server.integrationtest.TestParentKt.module
  security:
    ssl:
      keyStore: keystore/localhost.jks
      keyAlias: localhost
      keyStorePassword: localhosttest
      privateKeyPassword: localhosttest
